services:
  loan-webapp:
    build:
      context: ./loan-webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - shared_data:/app/data
    environment:
      - LENDING_WEBAPP_URL=https://lending-webapp:3001

  lending-webapp:
    build:
      context: .
      dockerfile: lending-webapp/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - loan-webapp
    volumes:
      - shared_data:/app/data
    environment:
      - LOAN_WEBAPP_URL=https://loan-webapp:3000

volumes:
  shared_data:
